### ISSUE TITLE
Guest Can View Homepage

### ISSUE THREAD

**Issue by jwperry** [jwperry/the_pivot#2]
As a guest,
When I visit "/",
Then I see "Freelancer",
And a link to "Browse by Poster",
And a link to "Browse by Category",
And a link to "Create Account",
And a link to "Log In"

**Comment by ToniRib** [comment]
Repurpose the existing test: UserSeesBrowseButtonOnLandingPageTest

**Comment by ToniRib** [comment]
Updated the homepage but will make a new issue for the testing of this functionality to be completed later.
