### ISSUE TITLE
Contractor Job Show

### ISSUE THREAD

**Issue by jwperry** [jwperry/the_pivot#40]
As a contractor,
When I visit the job show page,
And the job's bidding is open,
Then I see:
A link back to the category show
The name of the job
The full description of the job
Estimated duration tag
"Must be completed by" date
"Bidding ends" date
Total # of bids
Bid Range
Location of the job
Lister's Information showing:
Name as link to user show page
Rating
User's Picture
Number of active jobs
Number of completed jobs
"Active Since" date
"Place a Bid" accordion which has:
- My name
- Price box
- Duration estimate box
- Description box
- Submit bid button

**Comment by ToniRib** [comment]
Need to remember to update this user story to be more accurate
