### ISSUE TITLE
Lister Can Edit a Job

### ISSUE THREAD

**Issue by jwperry** [jwperry/the_pivot#47]
As a logged in lister,
When I visit my dashboard,
And I click on the "My Listings" table tab,
And I click on "Edit" for any open job,
Then I am redirected to an edit form that mirrors the create job form,
And when I update any fields,
And then I click "Update Job",
Then I am redirected to the job show,
And I see the updated information.

**Comment by danjwinter** [comment]
As per our discussion, listers will not be able to edit a job. If they make a mistake, they can cancel and re-create.
